[2025-06-04T05:16:10.037+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_etl_pipeline.extract scheduled__2025-06-03T00:00:00+00:00 [queued]>
[2025-06-04T05:16:10.043+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_etl_pipeline.extract scheduled__2025-06-03T00:00:00+00:00 [queued]>
[2025-06-04T05:16:10.044+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-04T05:16:10.054+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extract> on 2025-06-03 00:00:00+00:00
[2025-06-04T05:16:10.060+0000] {standard_task_runner.py:60} INFO - Started process 499 to run task
[2025-06-04T05:16:10.064+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'demo_etl_pipeline', 'extract', 'scheduled__2025-06-03T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/sample_etl_dag.py', '--cfg-path', '/tmp/tmpa3ugzeya']
[2025-06-04T05:16:10.067+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask extract
[2025-06-04T05:16:10.140+0000] {task_command.py:423} INFO - Running <TaskInstance: demo_etl_pipeline.extract scheduled__2025-06-03T00:00:00+00:00 [running]> on host 76ddeb3967d1
[2025-06-04T05:16:10.196+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='demo_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-06-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-03T00:00:00+00:00'
[2025-06-04T05:16:10.198+0000] {logging_mixin.py:188} INFO - âœ… Extracting data
[2025-06-04T05:16:10.199+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-04T05:16:10.206+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=demo_etl_pipeline, task_id=extract, execution_date=20250603T000000, start_date=20250604T051610, end_date=20250604T051610
[2025-06-04T05:16:10.237+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-04T05:16:10.259+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
